faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

llm:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0
    max_tokens: 2048

retriever:
  top_k: 10



